### ISSUE TITLE
ライセンスの付与

### ISSUE THREAD

**Issue by Kasugaccho** [sccp2020/defective-project#46]
ライセンスを明記するとより多くの開発者が利用できるツールになると思うので、ライセンスを付与することを提案します。

プロジェクトを応援しています。
CI使っていて、なおかつREADMEにビルド状況が記載されているのはのはとても良いですね。

**Comment by uzimaru0000** [comment]
授業で使ってるプロジェクトなので多くの開発者が利用することは想定していないです。
とりあえずcloseします。

**Comment by Kasugaccho** [comment]
これ、授業のプロジェクトだったんですね。

凄い面白そうなことをしていて良いなと思いました。
